# fly.toml app configuration file generated for tha-portal on 2024-05-22T19:22:05-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tha-portal'
primary_region = 'sea'

[deploy]
strategy = "rolling"

[env]
ADDRESS = "[::]:7878"
LOG_LEVEL = "infO"

OTEL_SERVICE_NAME = "portal"

[http_service]
internal_port = 7878
force_https = false

auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

processes = ["app"]

[http_service.http_options]
h2_backend = true

[http_service.concurrency]
type = "requests"
hard_limit = 1000
soft_limit = 750

[[http_service.checks]]
protocol = "http"
method = "GET"
path = "/health"

interval = "30s"
grace_period = "10s"
timeout = "5s"
