[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { version = "7.0", features = ["chrono"], default-features = false }
database.workspace = true
logging = { workspace = true, features = ["graphql"] }
