---
name: Deploy

"on":
  - push

jobs:
  composition:
    name: Check Schema Composition
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Hive CLI
        run: curl -sSL https://graphql-hive.com/install.sh | sh

      - run: hive schema:check ./schema.graphql --github --service portalq
        env:
          HIVE_TOKEN: ${{ secrets.HIVE_TOKEN }}
